theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - table
  - fullscreen
  - link
  - image
  - code
  - example
  - lists
  - spellchecker
  - textcolor
  - wordcount
style_formats:
  - {title : 'Fancybox', selector : 'a', classes : 'fancybox'}
  - {title : 'Table', selector : 'table', classes : 'table table-hover'}
  - {title : 'Center image', selector : 'img', styles: {margin-left: 'auto', margin-right: 'auto'}}
  - {title : 'Center iframe', selector : 'iframe', styles: {margin-left: 'auto', margin-right: 'auto'}}
extended_valid_elements : 
  - "iframe[src|width|height|name|align]"